/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Degree: typeof import('./src/components/Weather/Degree.vue')['default']
    Hourly: typeof import('./src/components/Weather/Hourly.vue')['default']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NTime: typeof import('naive-ui')['NTime']
    Props: typeof import('./src/components/Weather/Props.vue')['default']
    RainWarning: typeof import('./src/components/Weather/RainWarning.vue')['default']
    Realtime: typeof import('./src/components/Weather/Realtime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeatherIcon: typeof import('./src/components/Weather/WeatherIcon.vue')['default']
    Week: typeof import('./src/components/Weather/Week.vue')['default']
  }
}
